Transformation between freespace_trees and bitmaps
harshadjs/linux pull request #6
Opened 2020-07-13 17:37 UTC by YuexinLi

add freespace tree root struct with spinlocks 

add entries to freespace trees in ext4_sb_info

add init function for freespace trees

add freespace tree node struct

add freespace tree load/insert/can_merge functions

change units of freespcae_node_length from blks to clusters

fixed syntax bug and flex_index bug

delete debugging output messages

add tree_to_bitmap conversion functions

fix null pointer bug and offset bug in fuzzy search

2020-07-18 16:24 UTC, harshadjs requested changes
Code functionality looks good to me. The main thing that we need to work out is locking. If we do that now when we run parallel tests, our life will be much easier! Let's discuss this on monday! :)

2020-07-18 16:24 UTC, harshadjs commented on fs/ext4/mballoc.c
> +	if (prev_entry->offset + prev_entry->length == cur_entry->offset){
This can be collapsed to one line:

> return prev_entry->offset + prev_entry->length == cur_entry->offset;

2020-07-18 16:24 UTC, harshadjs commented on fs/ext4/mballoc.h
> +	unsigned int offset; /* Start block offset w.r.t. current flexible group*/
Usually these variables are named as `prefix_name`.  So maybe we can name these as frsp_offset and frsp_node?

2020-07-18 16:24 UTC, harshadjs commented on fs/ext4/mballoc.c
> +	if (groups_count % groups_per_flex == 0){
How about this?

```
flex_bg_count = (groups_count + groups_per_flex - 1) >> (sbi->s_es->s_log_groups_per_flex)?
```

2020-07-18 16:24 UTC, harshadjs commented on fs/ext4/mballoc.c
> +		return ret;
You can directly return -ENOMEM
```
return -ENOMEM;
```

2020-07-18 16:24 UTC, harshadjs commented on fs/ext4/mballoc.c
> +
Can you add a small description of what each function does above them in a comment? We prefer comments in /* */ form.

2020-07-18 16:24 UTC, harshadjs commented on fs/ext4/mballoc.c
> +		offset =  blk_no % (groups_per_flex*sbi->s_blocks_per_group);
It might be helpful to define a new function called ext4_get_flex_offset(sb, blkno).

2020-07-18 16:24 UTC, harshadjs commented on fs/ext4/mballoc.c
> +
A high level comment: we need to take the spinlock right before we start this loop and release it once we are done. If we lock and unlock on small critical sections, we may end up running into tricky race conditions.  I'll point them out below:

2020-07-18 16:24 UTC, harshadjs commented on fs/ext4/mballoc.c
> +		spin_unlock(&tree->frsp_t_lock);
See what happens in following situation:

You just inserted new_entry into the tree and you release the lock. This is okay for doing it during the initialization path, but if we do this during free path, we may find that immediately after adding this node, someone else grabbed this node and removed it from the tree. In that case, you might see that area allocated to new_node is now freed. So, we. may crash on line 2607.

So, it would be much easier to take the lock outside of this while loop and release it in the end.

2020-07-18 16:24 UTC, harshadjs commented on fs/ext4/mballoc.c
> +				kmem_cache_free(ext4_freespace_node_cachep, prev_entry);
It is dangerous to call kmem_cache_free() after taking a spin_lock(). On a uniprocessor system once you take a spinlock nobody else can run (they turn preemption off). If you sleep after doing that, nobody else can wake up and system will be hung. So we need to be careful about calling functions that can sleep after taking a spinlock. If we take lock outside of the loop one way to solve this problem is to set variables prev_entry (and also next_entry) only to be freed and at the end of while loop, have a check like this:

```
if (prev_entry)
    kmem_cache_free(ext4_freespace_node_cachep, prev_entry);
if (next_entry)
    kmem_cache_free(ext4_freespace_node_cachep, next_entry);
```

2020-07-18 16:24 UTC, harshadjs commented on fs/ext4/mballoc.c
> +		struct ext4_freespace_node *new_entry = kmem_cache_alloc(ext4_freespace_node_cachep, GFP_NOFS);
In Linux kernel, usually it's recommended that we define all the variables at the beginning of the function. It makes code more readable.

2020-07-20 20:03 UTC, YuexinLi commented on fs/ext4/mballoc.c
> +		spin_unlock(&tree->frsp_t_lock);
Yes!! Thanks for spotting this!!!!

2020-07-20 20:30 UTC, YuexinLi commented on fs/ext4/mballoc.c
> +				kmem_cache_free(ext4_freespace_node_cachep, prev_entry);
One while-loop may have multiple nodes to be freed, how to keep track of all of them across iterations: is it possible to keep all nodes to be freed in a list-ish(linked-list) object, then go through this list and free each item at the end of while loop?

2020-07-23 00:09 UTC, YuexinLi commented on fs/ext4/mballoc.c
> +				kmem_cache_free(ext4_freespace_node_cachep, prev_entry);
Solution: use mutex lock instead

2020-07-23 00:09 UTC, closed without merging